### ISSUE TITLE
Setup initial + tutorial

### ISSUE THREAD

**Issue by deakandrei** [deakandrei/XRproject#10]
Instalati Unity si faceti tutorialul urmator https://developers.google.com/ar/develop/unity/quickstart-android.

robotei

**Comment by Cristina-chan** [comment]
Tutorial pentru instalare Unity:
https://learn.unity.com/tutorial/create-your-first-unity-project?courseId=5c59cf22edbc2a001f59aa5d#

**Comment by Cristina-chan** [comment]
Un alt tutorial de Unity si ARCore:
https://codelabs.developers.google.com/codelabs/arcore-intro/#0

**Comment by deakandrei** [comment]
Fiecare să pună câte un screenshot cu o aplicație dintr-un tutorial în timp ce rulează pe telefon.

**Comment by Cristina-chan** [comment]
![Screenshot_20200322-210441_HelloAR U3D](https://user-images.githubusercontent.com/57443502/77258172-8075b480-6c81-11ea-9fb9-ba726f7b66ec.jpg)

**Comment by Cristina-chan** [comment]
![Screenshot_20200323-191147_Snake AR](https://user-images.githubusercontent.com/57443502/77343649-b1fe8680-6d3a-11ea-8cd6-631e1dae8d6d.jpg)

**Comment by RoscaAlexandra** [comment]
5 ore si 25 de taburi mai tarziu ( stupid jdk 8 si android sdk 👍  )
![WhatsApp Image 2020-03-24 at 01 17 17](https://user-images.githubusercontent.com/40744209/77372244-f0616900-6d6d-11ea-9330-3bb91489f190.jpeg)

**Comment by sz-eduard** [comment]
![WhatsApp Image 2020-03-24 at 11 52 42](https://user-images.githubusercontent.com/44710652/77412976-54fce200-6dc7-11ea-81bb-8386df8ea1d0.jpeg)
:D

**Comment by sibiceanurobert** [comment]
![WhatsApp Image 2020-03-28 at 16 26 45](https://user-images.githubusercontent.com/47791079/77825315-15106480-7111-11ea-9501-50f347b37164.jpeg)

**Comment by deakandrei** [comment]
![Screenshot_20200328-173112_TestAR](https://user-images.githubusercontent.com/58446056/77826806-56f1d880-711a-11ea-9959-9dc086967db4.jpg)

**Comment by RoscaAlexandra** [comment]
![WhatsApp Image 2020-03-30 at 01 03 26](https://user-images.githubusercontent.com/40744209/77862164-62302b80-7222-11ea-8b3a-b4ac683db15e.jpeg)

**Comment by GrigoreMihai** [comment]
I will assume it works 

![Screenshot_20200404-231719](https://user-images.githubusercontent.com/40674950/78460739-00613d00-76cc-11ea-8a31-d8c7bf077a05.png)
![Screenshot_20200404-231737](https://user-images.githubusercontent.com/40674950/78460745-10791c80-76cc-11ea-9419-4090d9a784c4.png)
