### ISSUE TITLE
Animarea caracterului

### ISSUE THREAD

**Issue by deakandrei** [deakandrei/XRproject#6]
Investigarea modelului prezentat in https://github.com/sebastianstarke/AI4Animation si rularea demo-ului respectiv in Unity.

Alte linkuri:
- https://xbpeng.github.io/projects/DeepMimic/index.html

Componenta din #4

**Comment by Cristina-chan** [comment]
Am rulat demo-ul in Unity, insa s-a dovedit prea dificil de integrat cu ARCore. Vom folosi alte modele 3D, in locul acestuia.
