### ISSUE TITLE
Detectarea persoanelor din video

### ISSUE THREAD

**Issue by deakandrei** [deakandrei/XRproject#7]
Sa se aleaga o retea pentru a detecta persoanele.

Este de preferat ca reteaua aleasa sa spuna si actiunile persoanelor si sa poata fi rulata in timp real. Astfel ar putea adresa 2 cerinte deodata.

Cateva link-uri:
1) http://gvv.mpi-inf.mpg.de/projects/wxu/MonoPerfCap/
2) http://gvv.mpi-inf.mpg.de/projects/VNect/
3) https://github.com/tensorflow/models/tree/master/research/object_detection
4) https://github.com/qubvel/segmentation_models.pytorch
5) https://github.com/rwightman/gen-efficientnet-pytorch

Componenta din #4 

In cazul in care sunt alese doua retele, una pentru detectare de persoane si una pentru recunoasterea actiunilor, sa se faca legatura intre ele.

**Comment by GrigoreMihai** [comment]
From what I've read a combination between 3 and 2 is what we want, ie. get persons using the library from 3 and the passing the video streem only from that regtangular frame provided to the library from 2 to give us the movements. As it seems kind of complicated I suggest we start with one person in front of phone camera and use number 2 to read the person movements and then emulate the special character of our according to that. After we manage that we can look into more complicated stuff.  

@AdiCovaci @deakandrei

**Comment by AdiCovaci** [comment]
https://pdfs.semanticscholar.org/06b1/47ba55f8e1e8371d2313c75996aea909791b.pdf

**Comment by AdiCovaci** [comment]
https://ieeexplore.ieee.org/document/4342799

**Comment by AdiCovaci** [comment]
Bun, deci m-am uitat toata saptamana pe papers, si eu personal cred ca asta pare cel mai ok, plus ca e un fail-safe bun in cazul in care vrem sa folosim ragdolls.

**Pose2Seg** face segmentare de instanta bazat pe postura si a fost acceptat la CVPR 2019.

https://arxiv.org/pdf/1803.10683.pdf
https://github.com/liruilong940607/Pose2Seg

Pare ca au deja reteaua preantrenata. O iau acum pe o masina sa o testez.

**Comment by AdiCovaci** [comment]
Alte idei:

https://github.com/foolwood/SiamMask
https://towardsdatascience.com/understanding-semantic-segmentation-with-unet-6be4f42d4b47

**Comment by GrigoreMihai** [comment]
https://github.com/dronefreak/human-action-classification

**Comment by AdiCovaci** [comment]
https://github.com/deakandrei/XRproject/issues/7#issuecomment-612970047 e un wrapper peste https://github.com/ildoonet/tf-pose-estimation

**Comment by Cristina-chan** [comment]
Alte link-uri:
https://github.com/dahburj/Barracuda-PoseNet
https://github.com/Jacob12138xieyuan/real-time-3d-pose-estimation-with-Unity3D
https://github.com/ildoonet/tf-pose-estimation
https://github.com/kenkra/Unity-3d-pose-baseline
https://github.com/digital-standard/ThreeDPoseUnityBarracuda

**Comment by Cristina-chan** [comment]
Am ales o retea de Pose Estimation 3D, MobileNet, pe care am convertit-o in Tensorflow Lite, pentru a putea rula pe Android.
