### ISSUE TITLE
Aspectul personajului virtual

### ISSUE THREAD

**Issue by deakandrei** [deakandrei/XRproject#8]
Alegere model 3D pentru personaj plus utilizarea style-transfer-ului pentru a schimba aspectul personajului.

https://github.com/zhanghang1989/PyTorch-Multi-Style-Transfer

Site pentru modele 3D:
https://poly.google.com/

Componenta din #4

**Comment by sibiceanurobert** [comment]
![1](https://user-images.githubusercontent.com/47791079/78458060-5aa3d300-76b7-11ea-8a9a-371f7c12c69d.png)

**Comment by RoscaAlexandra** [comment]
![WhatsApp Image 2020-04-04 at 20 49 39](https://user-images.githubusercontent.com/40744209/78458067-65f6fe80-76b7-11ea-836e-e7c9efbacd93.jpeg)
