### ISSUE TITLE
Interfata grafica + inputul video

### ISSUE THREAD

**Issue by deakandrei** [deakandrei/XRproject#9]
Sa se realizeze o interfata dummy pentru aplicatie pe baza user story-urilor existente (#18). Sa se puna toate butoanele necesare iar daca este posibil sa nu se acopere niciodata complet video-ul de la camera.

Sa se implementeze functionalitatea pentru butoanele de Play/Schimbare personaj. Sa se realizeze o interfata pentru aplicatia de Android.

**Comment by Cristina-chan** [comment]
Articol util pentru UI:
https://medium.com/adventures-in-ar/placing-different-objects-in-ar-using-on-screen-buttons-in-unity-arcore-ac3f446c35a
